M48
; DRILL file {KiCad (7.0.0)} date Thu Nov  9 16:36:12 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-09T16:36:12-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.375
%
G90
G05
T1
X114.75Y-94.884
X114.75Y-96.916
X119.83Y-95.9
T2
X116.655Y-93.36
X116.655Y-98.44
X119.83Y-93.36
X119.83Y-98.44
T0
M30
